
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: practicalaravel
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    volumes:
      - ./backend/Laravel:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: practicalaravel
      DB_USERNAME: root
      DB_PASSWORD: ""

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "3000:80" 
    depends_on:
      - backend

volumes:
  db_data:
    driver: local
